// <auto-generated />
namespace Shop_T_H.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202009271415499_initialDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
