// <auto-generated />
namespace Shop_T_H.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTagFieldProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTagFieldProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202011080212275_addTagFieldProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
